# Wazuh Manager Data Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
